Implemented add Opportunity
DeskproApps/salesforce pull request #13
Opened 2023-01-10 16:02 UTC by iTweeno

https://app.shortcut.com/deskpro/story/75729/salesforce-add-opportunity

2023-01-11 08:34 UTC, zpawn commented on src/pages/create/Opportunity.tsx
> +  const submit = async (data: any) => {
Why any? Let's typify submitting data

2023-01-11 08:34 UTC, zpawn commented on src/pages/create/Opportunity.tsx
> +            text={submitting ? "Creating..." : "Create"}
In this case, we usually `disabled` button and show the `loading` icon

here example https://github.com/DeskproApps/gitlab/blob/master/src/components/IssueForm/IssueForm.tsx#L127

2023-01-11 08:58 UTC, iTweeno commented on src/pages/create/Opportunity.tsx
> +  const submit = async (data: any) => {
Can't, the type comes from the metadata, I did this on activities and ash said i don't need it

2023-01-11 11:19 UTC, zpawn approved these changes

2023-01-12 09:26 UTC, AshleyDawson requested changes

2023-01-12 09:26 UTC, AshleyDawson commented on src/pages/create/Opportunity.tsx
> +        Name: z.string().min(1),
We always need to build the validation schema from sObject metadata as we can't guarantee these fields will exist or be mandatory.

There shouldn't be any circumstance where there are hard coded sObject fields.

2023-01-12 09:26 UTC, AshleyDawson commented on src/pages/create/Opportunity.tsx
> +        Name: z.string().min(1),
We always need to build the validation schema from sObject metadata as we can't guarantee these fields will exist or be mandatory.

There shouldn't be any circumstance where there are hard coded sObject fields.

2023-01-12 09:26 UTC, AshleyDawson commented on src/schemas/default.ts
> +      WhoId: z.string().min(1).optional(),
We always need to build the validation schema from sObject metadata as we can't guarantee these fields will exist or be mandatory.

There shouldn't be any circumstance where there are hard coded sObject fields.

(as above)

2023-01-12 12:09 UTC, AshleyDawson commented on src/pages/create/Opportunity.tsx
> +    register("StageName", {
What is the purpose of these hard-coded field names? `StageName` and `CloseDate`

2023-01-13 10:42 UTC, merged